# Step 0. Set-up

In [ ]:
import csv
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from datetime import datetime
import ast

In [ ]:
# Drive folder permissions
from google.colab import drive
drive.mount('/content/drive', force_remount = True)

Mounted at /content/drive

In [ ]:
# Change working directory
# os.chdir("drive/My Drive/CIS 5500 Final Project/data")
os.chdir("drive/My Drive/Courses/CIS 5500 Final Project/data")
!ls

# Step 1. Processing

In [ ]:
ratings_df = pd.read_csv('album_ratings.csv', 
                         delimiter = ',', skiprows = 0, lineterminator = '\n' )
ratings_df['Artist'] = ratings_df['Artist'].str.replace('&', 'and')
ratings_df['Title'] = ratings_df['Title'].str.replace('&', 'and')
ratings_df['Label'] = ratings_df['Label'].replace('&', 'and')
ratings_df = ratings_df.rename(
    columns = {'AOTY User Reviews\r': 'AOTY User Reviews'}
)

ratings_df[
    ["Artist", "Title", "Release Month", "Format", "Label", "Genre"]
] = ratings_df[
    ["Artist", "Title", "Release Month", "Format", "Label", "Genre"]
].astype(str)

ratings_df = ratings_df[ratings_df["Release Day"] != "ar"]
ratings_df = ratings_df[ratings_df["Release Day"] != "be"]
ratings_df = ratings_df[ratings_df["Release Day"] != "Ma"]
ratings_df = ratings_df[ratings_df["Release Day"] != "rc"]
ratings_df = ratings_df[ratings_df["Release Day"] != "ri"]
ratings_df = ratings_df[ratings_df["Release Day"] != "ul"]
ratings_df = ratings_df[ratings_df["Release Day"] != "un"]
ratings_df = ratings_df[ratings_df["Release Day"] != "us"]

ratings_df[
    ["Release Day", "Release Year", "AOTY Critic Score", "AOTY Critic Reviews", "AOTY User Score", "AOTY User Reviews"]
] = ratings_df[
    ["Release Day", "Release Year", "AOTY Critic Score", "AOTY Critic Reviews", "AOTY User Score", "AOTY User Reviews"]
].astype(np.int64, errors = "ignore")
ratings_df["Release Day"] = ratings_df["Release Day"].astype("Int64", errors = "ignore").astype(np.int64, errors = "ignore")
ratings_df['key'] = list(zip(ratings_df.Title.str.upper(), ratings_df.Artist.str.upper()))

ratings_df

,Artist,Title,Release Month,Release Day,Release Year,Format,Label,Genre,Metacritic Critic Score,Metacritic Reviews,Metacritic User Score,Metacritic User Reviews,AOTY Critic Score,AOTY Critic Reviews,AOTY User Score,AOTY User Reviews,key
0,Neko Case,Middle Cyclone,March,3,2009,LP,ANTI-,Alt-Country,79.0,31.0,8.7,31.0,79,25,78,55,"(MIDDLE CYCLONE, NEKO CASE)"
1,Jason Isbell and The 400 Unit,Jason Isbell and The 400 Unit,February,17,2009,LP,Thirty Tigers,Country Rock,70.0,14.0,8.4,7.0,73,11,73,8,"(JASON ISBELL AND THE 400 UNIT, JASON ISBELL A..."
2,Animal Collective,Merriweather Post Pavilion,January,20,2009,LP,Domino,Psychedelic Pop,89.0,36.0,8.5,619.0,92,30,87,1335,"(MERRIWEATHER POST PAVILION, ANIMAL COLLECTIVE)"
3,Bruce Springsteen,Working on a Dream,January,27,2009,LP,Columbia Records,Rock,72.0,29.0,7.9,101.0,70,23,66,38,"(WORKING ON A DREAM, BRUCE SPRINGSTEEN)"
4,Andrew Bird,Noble Beast,January,20,2009,LP,Fat Possum,Singer-Songwriter,79.0,29.0,8.7,47.0,74,24,78,44,"(NOBLE BEAST, ANDREW BIRD)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32353,Death Valley Girls,Under the Spell of Joy,October,2,2020,LP,Suicide Squeeze,nan,70.0,7.0,NaN,NaN,67,7,63,3,"(UNDER THE SPELL OF JOY, DEATH VALLEY GIRLS)"
32354,Gorillaz,"Song Machine, Season One: Strange Timez",October,23,2020,LP,nan,nan,80.0,11.0,9.3,44.0,75,8,94,4,"(SONG MACHINE, SEASON ONE: STRANGE TIMEZ, GORI..."
32355,Tobin Sprout,Empty Horses,September,18,2020,LP,Fire,nan,77.0,5.0,NaN,NaN,79,5,64,4,"(EMPTY HORSES, TOBIN SPROUT)"
32356,Jeremy Ivey,Waiting out the Storm,October,16,2020,LP,ANTI-,nan,82.0,4.0,NaN,NaN,77,3,64,3,"(WAITING OUT THE STORM, JEREMY IVEY)"
32357,Delmer Darion,Morning Pageants,October,16,2020,LP,Practise,nan,78.0,4.0,NaN,NaN,79,5,69,4,"(MORNING PAGEANTS, DELMER DARION)"

In [ ]:
print(ratings_df["Release Day"].unique())

In [ ]:
ratings_df.dtypes

In [ ]:
ratings_df.to_csv(r'final/Ratings.csv', index = False)

In [ ]:
ratings_small_df = ratings_df[:1000]
ratings_small_df.to_csv(r'final/Ratings_small.csv', index = False)

In [ ]:
artists_df = pd.read_csv('artists.csv', 
                         delimiter = ',', skiprows = 0)
artists_df

artists_df['artist'] = artists_df['artist_mb']
artists_df['country'] = np.where(artists_df['country_mb'], artists_df['country_mb'], 
                                 artists_df['country_lastfm'])
artists_df['tags'] = np.where(artists_df['tags_mb'], artists_df['tags_mb'], 
                              artists_df['tags_lastfm'])
artists_df['listeners'] = artists_df['listeners_lastfm']
artists_df['scrobbles'] = artists_df['scrobbles_lastfm']
artists_df['ambiguous'] = np.where(artists_df['ambiguous_artist'], 1, 0)
artists_df.drop(['mbid', 'artist_mb', 'artist_lastfm', 'country_mb', 
                 'country_lastfm','tags_mb', 'tags_lastfm', 'listeners_lastfm', 
                 'scrobbles_lastfm', 'ambiguous_artist'], axis = 1, inplace = True)
artists_df['key'] = artists_df['artist'].str.upper()
artists_df

In [ ]:
artists_df.to_csv(r'final/Artists.csv', index = False)

In [ ]:
reviews_df = pd.read_csv('reviews.csv', delimiter = ',', skiprows = 0)
reviews_df['Artist'] = reviews_df['Artist'].str.replace('&', 'and')
reviews_df['Title'] = reviews_df['Title'].str.replace('&', 'and')
reviews_df = reviews_df[reviews_df["Title"].isin(ratings_df["Title"])]
reviews_df = reviews_df[reviews_df["Artist"].isin(ratings_df["Artist"])]
reviews_df.dropna(inplace = True)
reviews_df

,Artist,Title,Source,Rating,Review,Reception
0,The Bird and the Bee,The Bird and the Bee,Delusions of Adequacy,70.0,"The Bird and the Bee is as light as a feather,...",Favorable
1,Pet Shop Boys,Yes,The A.V. Club,67.0,"On the surface, this big-sounding album belong...",Favorable
2,The Rapture,In The Grace of Your Love,Clash Music,70.0,"It's not a difficult or aloof album, but there...",Favorable
3,Death Cab For Cutie,Codes and Keys,Boston Globe,70.0,Here on Death Cab for Cutie's seventh record t...,Favorable
4,French Kicks,Two Thousand,Filter,78.0,[They've] caught on to what all those indies d...,Favorable
...,...,...,...,...,...,...
166264,Death Valley Girls,Under the Spell of Joy,Mojo,60.0,Pare things back to an insistent Banshees-like...,Mixed
166265,Gorillaz,"Song Machine, Season One: Strange Timez",DIY Magazine,90.0,Often Gorillaz records fall victim to feeling ...,Acclaim
166266,Gorillaz,"Song Machine, Season One: Strange Timez",AllMusic,70.0,"The likes of Robert Smith, Beck, St. Vincent, ...",Favorable
166267,Tobin Sprout,Empty Horses,Uncut,60.0,Sprout can get a little too earnest - greater ...,Mixed
166268,Jeremy Ivey,Waiting out the Storm,PopMatters,80.0,"There's no showing off or extended solos here,...",Favorable

In [ ]:
reviews_df.dtypes

In [ ]:
print(len(reviews_df["Title"].unique()))

In [ ]:
reviews_df.to_csv(r'final/Reviews.csv', index = False)

In [ ]:
songs_df = pd.read_csv('songs.csv', 
    converters={'artists': ast.literal_eval}, delimiter = ',', skiprows = 0)
songs_df['name'] = songs_df['name'].str.replace('&', 'and')
songs_df['album'] = songs_df['album'].str.replace('&', 'and')
songs_df['explicit'] = np.where(songs_df['explicit'], 1, 0)
songs_df['release_date'] = pd.to_datetime(songs_df['release_date'], errors = 'coerce')

songs_df['artists'] = songs_df['artists'].apply(lambda x: list(x))
songs_df = songs_df.explode("artists")
songs_df['artists'] = songs_df['artists'].str.replace('&', 'and')
songs_df = songs_df.drop_duplicates()
# songs_df = songs_df.rename(columns = {'artists': 'artist'}).reset_index()
songs_df.drop(['id', 'album_id', 'artist_ids'], axis = 1, inplace = True)

songs_df

,name,album,artists,track_number,disc_number,explicit,danceability,energy,key,loudness,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,year,release_date
0,Testify,The Battle Of Los Angeles,Rage Against The Machine,1,1,0,0.470,0.978,7,-5.399,...,0.0727,0.02610,0.000011,0.3560,0.503,117.906,210133,4.0,1999,1999-11-02
1,Guerrilla Radio,The Battle Of Los Angeles,Rage Against The Machine,2,1,1,0.599,0.957,11,-5.764,...,0.1880,0.01290,0.000071,0.1550,0.489,103.680,206200,4.0,1999,1999-11-02
2,Calm Like a Bomb,The Battle Of Los Angeles,Rage Against The Machine,3,1,0,0.315,0.970,7,-5.424,...,0.4830,0.02340,0.000002,0.1220,0.370,149.749,298893,4.0,1999,1999-11-02
3,Mic Check,The Battle Of Los Angeles,Rage Against The Machine,4,1,1,0.440,0.967,11,-5.830,...,0.2370,0.16300,0.000004,0.1210,0.574,96.752,213640,4.0,1999,1999-11-02
4,Sleep Now In the Fire,The Battle Of Los Angeles,Rage Against The Machine,5,1,0,0.426,0.929,2,-6.729,...,0.0701,0.00162,0.105000,0.0789,0.539,127.059,205600,4.0,1999,1999-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204020,Gospel of Juke,Notch - EP,FVLCRVM,2,1,0,0.264,0.966,5,-6.970,...,0.0672,0.00935,0.002240,0.3370,0.415,159.586,276213,4.0,2014,2014-01-09
1204021,Prism Visions,Notch - EP,FVLCRVM,3,1,0,0.796,0.701,11,-6.602,...,0.0883,0.10400,0.644000,0.0749,0.781,121.980,363179,4.0,2014,2014-01-09
1204022,Tokyo 360,Notch - EP,FVLCRVM,4,1,0,0.785,0.796,9,-5.960,...,0.0564,0.03040,0.918000,0.0664,0.467,121.996,385335,4.0,2014,2014-01-09
1204023,Yummy!,Notch - EP,FVLCRVM,5,1,0,0.665,0.856,6,-6.788,...,0.0409,0.00007,0.776000,0.1170,0.227,124.986,324455,4.0,2014,2014-01-09
1204024,That's The Way It Is,Notch - EP,FVLCRVM,6,1,0,0.736,0.708,2,-9.279,...,0.0539,0.01680,0.296000,0.2790,0.204,117.991,304982,4.0,2014,2014-01-09

In [ ]:
songs_albums_df = songs_df
songs_albums_df['key'] = list(zip(songs_albums_df.album.str.upper(), songs_albums_df.artists.str.upper()))
songs_albums_df = songs_albums_df.set_index('key').join(ratings_df[['key', 'Title', 'Artist']].set_index('key'), how = 'inner')
songs_albums_df['album'] = songs_albums_df['Title']
songs_albums_df['artists'] = songs_albums_df['Artist']
songs_albums_df = songs_albums_df.reset_index(drop = True)
songs_albums_df = songs_albums_df.drop_duplicates()
songs_albums_df = songs_albums_df.reset_index()
songs_albums_df.drop(['Title', 'Artist', 'index'], axis = 1, inplace = True)
songs_albums_df.rename(columns = {'artists': 'artist'}, inplace = True)

songs_albums_df

,name,album,artist,track_number,disc_number,explicit,danceability,energy,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,year,release_date
0,Shine A Little Light,"""Let's Rock""",The Black Keys,1,1,0,0.4400,0.719,-6.645,0,0.0445,0.0217,0.000005,0.0663,0.5230,111.398,196777,4.0,2019,2019-06-28
1,Eagle Birds,"""Let's Rock""",The Black Keys,2,1,0,0.5120,0.780,-4.946,0,0.0409,0.0471,0.024200,0.0856,0.6090,93.998,160543,4.0,2019,2019-06-28
2,Lo/Hi,"""Let's Rock""",The Black Keys,3,1,0,0.6060,0.679,-7.445,1,0.0321,0.0151,0.000433,0.0962,0.7070,122.016,177768,4.0,2019,2019-06-28
3,Walk Across The Water,"""Let's Rock""",The Black Keys,4,1,0,0.4180,0.583,-7.296,1,0.0257,0.3290,0.769000,0.2380,0.3270,79.594,235842,4.0,2019,2019-06-28
4,Tell Me Lies,"""Let's Rock""",The Black Keys,5,1,0,0.4360,0.626,-7.612,1,0.0361,0.2950,0.697000,0.1170,0.4090,94.643,219891,4.0,2019,2019-06-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57797,Slowness,~~~,Ana Roxanne,2,1,0,0.3930,0.302,-18.905,1,0.0372,0.9110,0.882000,0.3250,0.1910,79.048,260621,4.0,2019,2019-03-15
57798,It's a Rainy Day on the Cosmic Shore,~~~,Ana Roxanne,3,1,0,0.0815,0.737,-21.119,1,0.2480,0.8700,0.973000,0.1410,0.0654,50.642,320093,4.0,2019,2019-03-15
57799,Nocturne,~~~,Ana Roxanne,4,1,0,0.1830,0.135,-17.968,1,0.0407,0.9330,0.945000,0.1150,0.0399,126.901,336666,4.0,2019,2019-03-15
57800,I'm Every Sparkly Woman,~~~,Ana Roxanne,5,1,0,0.1610,0.340,-15.648,1,0.0523,0.9790,0.962000,0.0853,0.1180,218.026,143147,4.0,2019,2019-03-15
57801,In a Small Valley,~~~,Ana Roxanne,6,1,0,0.3130,0.957,-20.949,0,0.7030,0.7420,0.000361,0.6460,0.0346,128.733,324000,5.0,2019,2019-03-15

# Step 2. Exports

In [ ]:
songs_df[265300:].to_csv(r'final/Songs_265k.csv', index = False)
songs_artists_df[191800:].to_csv(r'final/SongsArtists_192k.csv', index = False)
# songs_albums_df.to_csv(r'final/SongsAlbums.csv', index = False)

In [ ]:
songs_df[265300:300000].to_csv(r'final/Songs_265k.csv', index = False)
songs_df[300000:330000].to_csv(r'final/Songs_300k.csv', index = False)
songs_df[330000:360000].to_csv(r'final/Songs_330k.csv', index = False)
songs_df[360000:390000].to_csv(r'final/Songs_360k.csv', index = False)
songs_df[390000:420000].to_csv(r'final/Songs_390k.csv', index = False)
songs_df[420000:450000].to_csv(r'final/Songs_420k.csv', index = False)
songs_df[450000:480000].to_csv(r'final/Songs_450k.csv', index = False)
songs_df[480000:510000].to_csv(r'final/Songs_480k.csv', index = False)
songs_df[510000:540000].to_csv(r'final/Songs_510k.csv', index = False)
songs_df[540000:570000].to_csv(r'final/Songs_540k.csv', index = False)
songs_df[570000:600000].to_csv(r'final/Songs_570k.csv', index = False)

In [ ]:
songs_df[600000:630000].to_csv(r'final/Songs_600k.csv', index = False)
songs_df[630000:660000].to_csv(r'final/Songs_630k.csv', index = False)
songs_df[660000:690000].to_csv(r'final/Songs_660k.csv', index = False)
songs_df[690000:720000].to_csv(r'final/Songs_690k.csv', index = False)
songs_df[720000:750000].to_csv(r'final/Songs_720k.csv', index = False)
songs_df[750000:780000].to_csv(r'final/Songs_750k.csv', index = False)
songs_df[780000:810000].to_csv(r'final/Songs_780k.csv', index = False)
songs_df[810000:840000].to_csv(r'final/Songs_810k.csv', index = False)
songs_df[840000:870000].to_csv(r'final/Songs_840k.csv', index = False)
songs_df[870000:900000].to_csv(r'final/Songs_870k.csv', index = False)

In [ ]:
songs_df[900000:930000].to_csv(r'final/Songs_900k.csv', index = False)
songs_df[930000:960000].to_csv(r'final/Songs_930k.csv', index = False)
songs_df[960000:990000].to_csv(r'final/Songs_960k.csv', index = False)
songs_df[990000:1020000].to_csv(r'final/Songs_990k.csv', index = False)
songs_df[1020000:1050000].to_csv(r'final/Songs_1020k.csv', index = False)
songs_df[1050000:1080000].to_csv(r'final/Songs_1050k.csv', index = False)
songs_df[1080000:1110000].to_csv(r'final/Songs_1080k.csv', index = False)
songs_df[1110000:1140000].to_csv(r'final/Songs_1110k.csv', index = False)
songs_df[1140000:1170000].to_csv(r'final/Songs_1140k.csv', index = False)
songs_df[1170000:1200000].to_csv(r'final/Songs_1170k.csv', index = False)

In [ ]:
songs_df[1200000:1230000].to_csv(r'final/Songs_1200k.csv', index = False)
songs_df[1230000:1260000].to_csv(r'final/Songs_1230k.csv', index = False)
songs_df[1260000:1290000].to_csv(r'final/Songs_1260k.csv', index = False)
songs_df[1290000:1320000].to_csv(r'final/Songs_1290k.csv', index = False)
songs_df[1320000:1350000].to_csv(r'final/Songs_1320k.csv', index = False)
songs_df[1350000:1380000].to_csv(r'final/Songs_1350k.csv', index = False)
songs_df[1380000:1410000].to_csv(r'final/Songs_1380k.csv', index = False)
songs_df[1410000:1440000].to_csv(r'final/Songs_1410k.csv', index = False)
songs_df[1440000:1470000].to_csv(r'final/Songs_1440k.csv', index = False)
songs_df[1470000:1500000].to_csv(r'final/Songs_1470k.csv', index = False)

In [ ]:
songs_df[1500000:1530000].to_csv(r'final/Songs_1500k.csv', index = False)
songs_df[1530000:1560000].to_csv(r'final/Songs_1530k.csv', index = False)
songs_df[1560000:1590000].to_csv(r'final/Songs_1560k.csv', index = False)
songs_df[1590000:1620000].to_csv(r'final/Songs_1590k.csv', index = False)
songs_df[1620000:1650000].to_csv(r'final/Songs_1620k.csv', index = False)
songs_df[1650000:1680000].to_csv(r'final/Songs_1650k.csv', index = False)
songs_df[1680000:1710000].to_csv(r'final/Songs_1680k.csv', index = False)
songs_df[1710000:1740000].to_csv(r'final/Songs_1710k.csv', index = False)
songs_df[1740000:1770000].to_csv(r'final/Songs_1740k.csv', index = False)
songs_df[1770000:].to_csv(r'final/Songs_1770k.csv', index = False)